name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: npm ci && npm run build
      - run: npm run lint
      - run: npm run format
      - run: aws s3 sync ./build/ s3://nucleoid.com --delete
      - run: aws cloudfront create-invalidation --distribution-id E16QJ9JAP21GVP --paths "/*"
